/**
 * Invite codes are 12 lowercase hex characters as generated by the DB
 * default (`encode(gen_random_bytes(6), 'hex')` in migration 001).
 * Users see + paste them with optional hyphens, spaces, and casing -- we
 * normalize to the canonical 12-char lowercase form before any DB call.
 */

const INVITE_CODE_HEX_LENGTH = 12;
const INVITE_CODE_PATTERN = /^[0-9a-f]{12}$/;

/** Strip whitespace + dashes, lowercase. */
export function normalizeInviteCode(input: string): string {
  return input.trim().toLowerCase().replace(/[\s-]+/g, '');
}

/** True if the input -- after normalization -- is a valid invite code. */
export function isValidInviteCode(input: string): boolean {
  return INVITE_CODE_PATTERN.test(normalizeInviteCode(input));
}

/** Pretty-print as XXXX-XXXX-XXXX in uppercase for UI display. */
export function formatInviteCodeForDisplay(code: string): string {
  const norm = code.replace(/[\s-]+/g, '').toUpperCase();
  if (norm.length !== INVITE_CODE_HEX_LENGTH) return norm;
  return norm.match(/.{1,4}/g)!.join('-');
}
